# frozen_string_literal: true

module Unit
  extend ActiveSupport::Concern

  included do
    include Titleable
    include Mappable
    include UnitThumbnailUploader::Attachment(:thumbnail)
    include DescriptionSanitation

    validates :number, presence: true
    enum :status, {
      autogenerated: 0,
      validated: 1
    }
  end
end
