class Types::Enum::MappingExternalSite < Types::Enum::Base
  value 'MY_ANIME_LIST_ANIME', value: 'myanimelist/anime'
  value 'MY_ANIME_LIST_MANGA', value: 'myanimelist/manga'
  value 'ANILIST_ANIME', value: 'anilist/anime'
  value 'ANILIST_MANGA', value: 'anilist/manga'
  value 'THE_TVDB', value: 'thetvdb'
  value 'THE_TVDB_SERIES', value: 'thetvdb/series'
  value 'THE_TVDB_SEASON', value: 'thetvdb/season'
  value 'ANI_DB', value: 'anidb'
  value 'ANIME_NEWS_NETWORK', value: 'animenewsnetwork'
  value 'MANGA_UPDATES', value: 'mangaupdates'
  value 'HULU', 'hulu'
  value 'IMDB_EPISODES', value: 'imdb/episodes'
  value 'AOZORA', value: 'aozora'
  value 'TRAKT', value: 'trakt'
  value 'MY_DRAMA_LIST', value: 'mydramalist'
end
